### ISSUE TITLE
移动速率太快

### ISSUE THREAD

**Issue by taozhiyu** [mumuy/pacman#8]
![](https://pic.rmb.bdstatic.com/bjh/38f17a56afd2b79b8210707f853953b5.gif)
（如果gif加载不了可以访问[这里](https://pic.rmb.bdstatic.com/bjh/38f17a56afd2b79b8210707f853953b5.gif)）

gif的录制看起来经常在漂移，因为采样率不足，但是gif的时长是1:1的（右边有实时在线时间）

**Comment by mumuy** [comment]
我好像是以屏幕刷新率更新画布的，估计你屏幕很好，刷新率太高了

**Comment by taozhiyu** [comment]
（确实。。。240Hz的。。。）

**Comment by mumuy** [comment]
可以试试，应该已经解决了

**Comment by taozhiyu** [comment]
移动的问题解决了，但是 #7 的问题还存在，先关闭这个issue
